# Makefile for dirlib ~/h/PROJECT
# Created by NAME on:  DATE (e.g. run "date")


here		= PROJECT

includes	= INCLUDE_FILES

sources		= SOURCE FILES (not including main.c)

siblings	= LIST PROJECTS YOUR PROJECT NEEDS


include ../gmake-magic/Make.common
